
# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5100
    onOpen: ignore
    visibility: public
  - port: 6379
    onOpen: ignore
  - port: 27017
    onOpen: ignore
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: DB
    command: |
      docker-compose up redis mongodb
  - name: Steedos Platform
    command: |
      echo "ROOT_URL=$(gp url 5100)" >> .env.local
      yarn
      yarn build
      yarn start

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - redhat.vscode-yaml
    - steedos.steedosdx-vscode
    - steedos.steedosdx-vscode-core
    - ms-ceintl.vscode-language-pack-zh-hans
