version: "3.9"

services:

  steedos:
    image: steedos/steedos-enterprise:2.7.10-beta.8
    ports:
      - "5000:5000"    # Steedos
      - "27017:27017"  # MongoDB
      - "9001:9001"    # Supervisor
      - "6379:6379"    # Redis
    env_file:
      - .env
      - .env.local
    volumes:
      - "./steedos-storage:/steedos-storage"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: steedos
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pg2024
    ports:
      - "5432:5432"
    volumes:
      - ./steedos-storage/postgres_data:/var/lib/postgresql/data